[package]
name = "tust-portal-desktop"
version = "0.1.0"
description = "天科大校园网自动登录"
authors = ["oneepointer"]
edition = "2021"

[lib]
name = "tust_portal_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = [
    "rustls-tls",
], default-features = false }
tokio = { version = "1", features = ["time", "sync", "process"] }
chrono = { version = "0.4", features = ["serde"] }
local-ip-address = "0.6"
urlencoding = "2"
tracing = "0.1"
tracing-subscriber = "0.3"
